### ISSUE TITLE
eof, stopped parse proc: should only happen on mpv termination

### ISSUE THREAD

**Issue by revantjhalani** [derlaft/synco#2]
Hey, so I set everything up according to the readme (although I did have some trouble with the concept of helper.lua, for now ive cloned the repository and set the path for helper.lua inside the synco_client directory. 
The errors I'm receiving are, 
On the server:   
command: ./synco_server 127.0.0.1:4042
output: "2020/06/17 23:26:57 Client 1234 registered
             2020/06/17 23:26:57 rpc error: code = Canceled desc = context canceled
             2020/06/17 23:26:57 Client 1234 deregistered"
On client: 
command: ./go/bin/synco_client /mnt/hgfs/Shared/testfiles/test1.mp4
output: 2020/06/17 23:30:19 eof
            2020/06/17 23:30:19 stopped parse proc: should only happen on mpv termination
Any help would be appreciated. Thanks.
![Screenshot (11)](https://user-images.githubusercontent.com/39228530/84986673-90a40f80-b15c-11ea-8b89-16406c9e0589.png)

**Comment by derlaft** [comment]
Hey,

thanks for the interest for the project!

The problem is with the recent mvp update.

To fix the problem, I've completely rewritten the whole project.

You can find the result in branch `new`.

Let me know if that works for you.

**Comment by derlaft** [comment]
Since I've already tested the new version a lot, I updated the master branch & readme too.

**Comment by revantjhalani** [comment]
Thank you so much! It works! 
I hope it won't be too much of a hassle for you to clear a few doubts of mine:
1: I just tested this with two clients, one of the clients was lagging behind the other one by a few milliseconds. Is there any way for me to specify the offset?
2: After most commands such as seek, pause the clients go back to the status of "not ready" (they do seek, but I have to manually press F1 for both clients for them to start again. (I suppose this is set in helper.lua, please confirm if true)
3: Is there any way to send commands from the server directly, like pause, seek, etc

I hope this is not too much of a bother. If you could just point me in the right direction that'd be awesome. Thanks.

**Comment by derlaft** [comment]
>1: I just tested this with two clients, one of the clients was lagging behind the other one by a few milliseconds. Is there any way for me to specify the offset?

Server has a flag - `max-desync`. By default, it is set to 5 seconds. This is made to ensure that synco works over slow networks. It was never made to ensure real-time millisecond-precise accuracy.

>2: After most commands such as seek, pause the clients go back to the status of "not ready" (they do seek, but I have to manually press F1 for both clients for them to start again. (I suppose this is set in helper.lua, please confirm if true)

That unfortunately really depends on the file and container and how aggressively you send commands :)

If you seek by small amounts of time (for example, with right/left key in mpv) this works just fine without stopping.

The current protocol works like this: server sends "server time" all the time, and if any client is `max-desync` time away from it, it stops. Of course it also seeks on events.

Unfortunately, this system is not perfect. I could not make seeking work very reliably, because every container is slightly different. For example, imagine this situation:

* you seek to 10.5001 seconds.
* mpv acknowledges seek and it confirms that is actually changed file position to 10.5001 seconds
* however, after a few milliseconds, it realizes that it is not possible to start playback from this time
* and instead it starts playing from 10.6 seconds. In some containers, the difference is huge (and it starts playing from 25.0, or even 55.0 seconds)
* from my understanding, mpv sends no event about such a situation

I am continuing fiddling around and trying to make this work perfectly, but right now I have not found the solution.

The workaround for me me was just to use files which allow to seek precisely. This way the situation you have described only happens when you send too many commands at the same time.

 >I suppose this is set in helper.lua, please confirm if true

There is no `helper.lua` anymore :) The new version uses `--input-ipc-server` feature of mpv. The key is set in the file `cmd/synco_client/commands.go`.

>3: Is there any way to send commands from the server directly, like pause, seek, etc

It should be easily possible, thought it is not the idea of synco. The project was made for a few clients to have equal amount of control over playback. If you need some centralized control, you have to make some changes.

Hope that answers your questions.
